{{- if .Values.netpolicy }}
{{- if .Values.netpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      selector.cilium/release: {{ .Release.Name }}
  policyTypes:
  - Egress
  egress:
  {{- range .Values.netPolicies }}
  - to:
    - podSelector:
        matchLabels:
          {{- if .group }}
          selector.cilium/group: {{ .group }}
          {{- else }}
          selector.cilium/release: {{ .name }}
          {{- end }}
    ports:
    {{- range .filters }}
    - protocol: {{ .type }}
      port: {{ .port }}
      {{- if .endPort }}
      endPort: {{ .endPort }}
      {{- end}}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
