{{- if .Values.cilium }}
{{- if .Values.cilium.enabled }}
{{- if .Values.podToEntitiesAccess }}
{{- range .Values.podToEntitiesAccess }}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .name }}-to-entities
  namespace: {{ .namespace | default $.Release.Namespace }}
specs:
  - endpointSelector:
      matchLabels:
        {{- if .podLabel }}
        selector.cilium/release: {{ .podLabel }}
        {{- else }}
        {{ .customLabel }}
        {{- end }}
    egress:
    - toEntities:
      {{- with .entities }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- if .services }}
    - toServices:
      {{- with .services }}
        {{- toYaml . | nindent 6}}
      {{- end }}
    {{- end }}
  - endpointSelector:
      matchLabels:
        {{- if .podLabel }}
        selector.cilium/release: {{ .podLabel }}
        {{- else }}
        {{ .customLabel }}
        {{- end }}
    ingress:
    - fromEntities:
      {{- with .entities }}
        {{- toYaml . | nindent 6}}
      {{- end }}
    {{- if .services }}
    - fromServices:
      {{- with .services }}
        {{- toYaml . | nindent 6}}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}