{{- if .Values.nsAccessPolicy }}
{{ range .Values.nsAccessPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .fromNamespace }}-to-{{ .namespace }}-ingress
  namespace: {{ .namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .fromNamespace }}
{{- end }}
{{- end }}